### PR TITLE
Setup weekly meeting posts

### PR DESCRIPTION
**Pull request by crollins18**

### CODE REVIEW

**Review by kapravel — COMMENTED** [review]
Hey @crollins18, I think it would be better if the links to youtube were clickable (actual links). What do you think?

**Comment by crollins18** [comment]
@kapravel 
Me and Dom did some additional work and decided to go with iframes of each video instead of the straight links to youtube.

**Comment by crollins18** [comment]
Thoughts?

**Comment by kapravel** [comment]
yeah, that would work too!

**Comment by crollins18** [comment]
@kapravel only issue is it takes a while to load the page with all the iframe youtube videos. It is not that bad right now, but I am thinking scalability. I am trying to see if I can make each video only load when the card/container is expanded.

**Comment by kapravel** [comment]
That's a legit concern, but I believe that we can do some pagination in Jekyll/Github Pages if we see that the page is getting significantly slower!

**Pull request merged**
