### PR TITLE
Weekly challenge page #21

### PR DESCRIPTION
**Pull request by napkinbrown**
Capture

### CODE REVIEW

**Comment by John123Allison** [comment]
Maybe a tutorial for how to use the hash for new users. Otherwise LGTM

**Comment by napkinbrown** [comment]
@John123Allison 
I just added a flag checker, cause why not
checker_1
checker_2
checker_3

**Comment by napkinbrown** [comment]
Cleanup
cleanup

**Comment by John123Allison** [comment]
LGTM

**Pull request merged**
